# Generated by Django 5.2.8 on 2025-11-20 20:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome público da estratégia.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descrição de marketing e técnica."
                    ),
                ),
                (
                    "assets",
                    models.CharField(
                        default="",
                        help_text="Ativos que a estratégia opera (ex: EURUSD,XAUUSD).",
                        max_length=255,
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("M1", "1 Minuto"),
                            ("M5", "5 Minutos"),
                            ("M15", "15 Minutos"),
                            ("M30", "30 Minutos"),
                            ("H1", "1 Hora"),
                            ("H4", "4 Horas"),
                            ("D1", "Diário"),
                        ],
                        default="M15",
                        help_text="Timeframe principal da execução.",
                        max_length=10,
                    ),
                ),
                (
                    "portfolio_composition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON com os parâmetros da estratégia.",
                    ),
                ),
                (
                    "suggested_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=500.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "backtest_period_days",
                    models.IntegerField(
                        default=730,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("SINGLE_PORTFOLIO", "Ativo Único / Portfólio"),
                            ("PAIRS", "Pairs Trading"),
                        ],
                        default="SINGLE_PORTFOLIO",
                        max_length=20,
                    ),
                ),
                (
                    "strategy_file",
                    models.CharField(
                        help_text="Nome do arquivo Python da estratégia (sem .py).",
                        max_length=100,
                    ),
                ),
                (
                    "ml_model_path",
                    models.FileField(
                        blank=True,
                        help_text="Caminho para o modelo de IA treinado.",
                        null=True,
                        upload_to="ml_models/",
                    ),
                ),
                (
                    "ml_threshold",
                    models.FloatField(
                        default=0.55,
                        help_text="Limiar de probabilidade (0-1) para a IA aprovar um trade.",
                    ),
                ),
                (
                    "backtest_results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Resultados numéricos do último backtest.",
                    ),
                ),
                (
                    "aura_analysis",
                    models.TextField(
                        blank=True, help_text="Análise qualitativa da IA (LLM)."
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="ID da última tarefa Celery associada.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Controla a visibilidade no marketplace.",
                    ),
                ),
                (
                    "magic_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Número mágico para identificar as ordens no MT5.",
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estratégia",
                "verbose_name_plural": "Estratégias",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Sucesso"),
                            ("INFO", "Informativo"),
                            ("WARNING", "Aviso"),
                            ("ERROR", "Erro"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActiveRobotInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot_size",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Lote fixo a ser usado nas operações (se risk_mode for FIXED).",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_robot_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_instances",
                        to="trading_platform.strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instância de Robô Ativa",
                "verbose_name_plural": "Instâncias de Robôs Ativas",
            },
        ),
        migrations.CreateModel(
            name="TradingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="Apelido para a conta",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "account_login",
                    models.CharField(
                        help_text="O número de login da conta, deve ser único.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("server", models.CharField(max_length=100)),
                ("encrypted_password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Sucesso"),
                            ("FAILED", "Falhou"),
                            ("EXCEPTION", "Exceção"),
                            ("IGNORED", "Ignorado"),
                            ("CLOSED", "Fechado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("symbol", models.CharField(blank=True, max_length=50)),
                ("trade_type", models.CharField(blank=True, max_length=20)),
                (
                    "volume",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_entry",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "price_exit",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sl_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "tp_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("retcode", models.BigIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "order_ticket",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID do ticket usado em sistemas legados ou de backtest (ex: MT5).",
                        null=True,
                    ),
                ),
                (
                    "broker_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID da ordem retornado pela corretora (ex: FIX OrderID).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Duração total da operação desde a abertura até o fechamento.",
                        null=True,
                    ),
                ),
                (
                    "ai_probability",
                    models.FloatField(
                        blank=True,
                        help_text="Probabilidade de sucesso calculada pela IA no momento da abertura.",
                        null=True,
                    ),
                ),
                (
                    "ai_decision_features",
                    models.JSONField(
                        blank=True,
                        help_text="Features que mais influenciaram a decisão da IA.",
                        null=True,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade_logs",
                        to="trading_platform.activerobotinstance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trading_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_platform.tradingaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Trade",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="activerobotinstance",
            name="trading_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_robot_instances",
                to="trading_platform.tradingaccount",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de telefone do usuário.",
                        max_length=20,
                    ),
                ),
                (
                    "favorite_tickers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de símbolos favoritos do usuário.",
                    ),
                ),
                (
                    "global_drawdown_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Limite de Drawdown Diário Global (%). Se atingido, todos os robôs são pausados.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "max_open_positions",
                    models.IntegerField(
                        default=5,
                        help_text="Número máximo de posições abertas simultaneamente em todas as contas.",
                    ),
                ),
                (
                    "max_risk_per_trade",
                    models.FloatField(
                        default=1.0,
                        help_text="Risco máximo por trade, como uma porcentagem do saldo da conta (ex: 1.0 para 1%).",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="activerobotinstance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "strategy"),
                name="unique_active_strategy_per_user",
            ),
        ),
    ]
