# Generated by Django 5.2.8 on 2025-11-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_platform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activerobotinstance",
            name="risk_mode",
            field=models.CharField(
                choices=[("FIXED", "Lote Fixo"), ("DYNAMIC", "Risco Dinâmico (%)")],
                default="FIXED",
                help_text="Modo de cálculo do tamanho da posição.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="activerobotinstance",
            name="risk_percent",
            field=models.FloatField(
                default=1.0,
                help_text="Porcentagem do saldo a arriscar por trade (se risk_mode for DYNAMIC). Ex: 1.0 = 1%.",
            ),
        ),
    ]
