# Generated by Django 5.2.8 on 2025-11-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_platform", "0002_activerobotinstance_risk_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingaccount",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Saldo atual da conta (atualizado periodicamente).",
                max_digits=15,
            ),
        ),
    ]
