# Generated by Django 5.0 on 2026-01-18 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0003_tradingaccount_current_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assets_interest', models.JSONField(help_text="Lista de ativos de interesse (ex: ['Stocks', 'Crypto']).")),
                ('risk_profile', models.CharField(max_length=50)),
                ('objective', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falhou')], default='PENDING', max_length=20)),
                ('result_json', models.JSONField(blank=True, help_text='Resposta estruturada da IA.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
