# Generated by Django 5.0 on 2026-01-25 22:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0004_portfolioanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activerobotinstance',
            name='risk_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Porcentagem do saldo a arriscar por trade (se risk_mode for DYNAMIC). Ex: 1.00 = 1%.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_risk_per_trade',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Risco máximo por trade, como uma porcentagem do saldo da conta (ex: 1.00 para 1%).', max_digits=5),
        ),
    ]
