# Generated by Django 5.0 on 2026-02-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0005_migrate_risk_fields_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingaccount',
            name='trading_protocol',
            field=models.CharField(choices=[('MT5', 'MetaTrader 5'), ('FIX', 'FIX Protocol (cTrader)')], default='MT5', help_text='Protocolo usado para enviar ordens ao broker', max_length=10, verbose_name='Protocolo de Trading'),
        ),
    ]
