# Generated by Django 5.0 on 2026-02-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_platform', '0006_tradingaccount_trading_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falhou'), ('EXCEPTION', 'Exceção'), ('IGNORED', 'Ignorado'), ('CLOSED', 'Fechado')], max_length=30),
        ),
    ]
