name: projeto_trader_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas=1.5.3
  - numpy
  - scikit-learn
  - xgboost
  - pandas-ta
  - pip
  - pip:
    - django
    - djangorestframework
    - django-cors-headers
    - django-background-tasks
    - MetaTrader5
    - backtesting
    - joblib
    - waitress
    - gunicorn
    - dj-database-url
    - psycopg2-binary
    - whitenoise
    - simplefix
